package com.example.app

fun main() {
    println("Kotlin application started.")
    val headerClass = "text-3xl font-extrabold text-green-700 leading-tight"
    val buttonClass = "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"

    println("Kotlin code using Tailwind classes: $headerClass and $buttonClass")

    // Example of a string that might be part of an HTML template generated by Kotlin
    val generatedHtmlSnippet = """
        <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl m-4">
            <div class="md:flex">
                <div class="p-8">
                    <div class="uppercase tracking-wide text-sm text-indigo-500 font-semibold">Kotlin Generated Content</div>
                    <a href="#" class="block mt-1 text-lg leading-tight font-medium text-black hover:underline">Dynamic Tailwind classes from Kotlin</a>
                    <p class="mt-2 text-gray-500">This is an example of content where Tailwind CSS classes (`text-gray-500`, `max-w-md`, etc.) might be present in Kotlin strings or DSLs for web frameworks.</p>
                </div>
            </div>
        </div>
    """.trimIndent()
    println(generatedHtmlSnippet)
}
